"use client";

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { updateProfile } from 'firebase/auth';
import { onAuthStateChanged } from 'firebase/auth';
import { auth } from '../../firebase/clientApp';
import { getUserProfile, isUsernameTaken, createUserProfile, getUserProfileByEmail } from '../../services/userService';

export default function ProfileSetup() {
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [username, setUsername] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const [autoGeneratedUsername, setAutoGeneratedUsername] = useState(false);
  const [touchedFields, setTouchedFields] = useState<Record<string, boolean>>({});
  const [customValidation, setCustomValidation] = useState<Record<string, string>>({});
  const [usernameAvailable, setUsernameAvailable] = useState<boolean | null>(null);
  const [isCheckingUsername, setIsCheckingUsername] = useState(false);
  const [currentUserUid, setCurrentUserUid] = useState<string | null>(null);
  const [userEmail, setUserEmail] = useState<string>('');
  
  const router = useRouter();

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (user) => {
      if (user) {
        setCurrentUserUid(user.uid);
        setUserEmail(user.email || '');
        
        // Try to get existing profile
        try {
          const profile = await getUserProfile(user.uid);
          if (profile) {
            setFirstName(profile.firstName);
            setLastName(profile.lastName);
            setUsername(profile.username);
            
            // Check if username appears to be auto-generated (contains email name plus numbers)
            const emailPrefix = user.email?.split('@')[0] || '';
            if (profile.username.startsWith(emailPrefix) && /\d{1,4}$/.test(profile.username)) {
              setAutoGeneratedUsername(true);
            }
            
            checkUsername(profile.username);
          } else {
            // No profile exists, set default values from auth
            const displayName = user.displayName || '';
            const nameParts = displayName.split(' ');
            setFirstName(nameParts[0] || '');
            setLastName(nameParts.slice(1).join(' ') || '');
            setUsername(user.email?.split('@')[0] || '');
            
            if (user.email) {
              checkUsername(user.email.split('@')[0]);
            }
          }
        } catch (error) {
          console.error('Error fetching user profile:', error);
          setError('Failed to load your profile. Please try refreshing the page.');
        } finally {
          setIsLoading(false);
        }
      } else {
        // Not signed in, redirect to login
        router.push('/login');
      }
    });
    
    return () => unsubscribe();
  }, [router]);

  const handleBlur = (e: React.FocusEvent<HTMLInputElement>) => {
    const { name, value, validity } = e.target;
    setTouchedFields({ ...touchedFields, [name]: true });
    
    // Clear previous validation message
    setCustomValidation({ ...customValidation, [name]: '' });
    
    // Add a custom validation message if empty
    if (validity.valueMissing) {
      let message = 'This field is required';
      if (name === 'firstName') message = 'Please enter your first name';
      if (name === 'lastName') message = 'Please enter your last name';
      if (name === 'username') message = 'Please choose a username';
      
      setCustomValidation({ ...customValidation, [name]: message });
    }
  };

  const checkUsername = async (username: string) => {
    if (username.length < 2) {
      setUsernameAvailable(null);
      return;
    }
    
    try {
      setIsCheckingUsername(true);
      const taken = await isUsernameTaken(username);
      
      if (taken) {
        // If username is taken, check if it belongs to the current user
        // (either by UID or by email)
        if (currentUserUid && userEmail) {
          const profileByUid = await getUserProfile(currentUserUid);
          const profileByEmail = await getUserProfileByEmail(userEmail);
          
          // Check if the username belongs to either profile
          const isOwnUsername = (profileByUid?.username === username.toLowerCase()) || 
                               (profileByEmail?.username === username.toLowerCase());
          
          setUsernameAvailable(isOwnUsername);
        } else {
          setUsernameAvailable(false);
        }
      } else {
        // Username is not taken, so it's available
        setUsernameAvailable(true);
      }
    } catch (error) {
      console.error('Error checking username:', error);
      setUsernameAvailable(false);
    } finally {
      setIsCheckingUsername(false);
    }
  };

  const handleUsernameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setUsername(value);
    
    // Debounce the username check
    const timeoutId = setTimeout(() => {
      if (value.length >= 2) {
        checkUsername(value);
      } else {
        setUsernameAvailable(null);
      }
    }, 500);
    
    return () => clearTimeout(timeoutId);
  };

  const validateForm = () => {
    const newValidation: Record<string, string> = {};
    const newTouchedFields: Record<string, boolean> = {};
    let isValid = true;
    
    // First name validation
    newTouchedFields.firstName = true;
    if (!firstName.trim()) {
      newValidation.firstName = 'Please enter your first name';
      isValid = false;
    }
    
    // Last name validation
    newTouchedFields.lastName = true;
    if (!lastName.trim()) {
      newValidation.lastName = 'Please enter your last name';
      isValid = false;
    }
    
    // Username validation
    newTouchedFields.username = true;
    if (!username.trim()) {
      newValidation.username = 'Please choose a username';
      isValid = false;
    } else if (username.length < 2) {
      newValidation.username = 'Username must be at least 2 characters';
      isValid = false;
    } else if (usernameAvailable === false) {
      newValidation.username = 'This username is already taken';
      isValid = false;
    }
    
    setTouchedFields({ ...touchedFields, ...newTouchedFields });
    setCustomValidation({ ...customValidation, ...newValidation });
    
    return isValid;
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    
    if (!validateForm() || !currentUserUid) return;
    
    setIsSaving(true);
    setError('');
    setSuccess(false);
    
    try {
      // Update the user profile in Firestore
      await createUserProfile(currentUserUid, {
        firstName,
        lastName,
        username,
        email: userEmail
      });
      
      // Update the display name in Firebase Auth
      if (auth.currentUser) {
        await updateProfile(auth.currentUser, {
          displayName: username
        });
      }
      
      setSuccess(true);
      
      // Redirect to interest selection page after a short delay
      setTimeout(() => {
        router.push('/select-interests');
      }, 1500);
    } catch (err: unknown) {
      let errorMessage = 'Failed to update your profile';
      if (err instanceof Error) {
        if (err.message.includes('Username is already taken')) {
          errorMessage = 'This username is already taken';
          setCustomValidation({ ...customValidation, username: 'This username is already taken' });
        }
      }
      setError(errorMessage);
      console.error(err);
    } finally {
      setIsSaving(false);
    }
  };

  // Show validation styling only if field is touched
  const getInputClasses = (fieldName: string) => {
    const baseClasses = "w-full px-4 py-3 bg-white border border-neutral-300 rounded-lg shadow-sm transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-amber-500 focus:border-amber-500 placeholder-neutral-400 text-neutral-700";
    
    if (touchedFields[fieldName] && customValidation[fieldName]) {
      return `${baseClasses} border-red-400 focus:ring-red-400 focus:border-red-400 bg-red-50 text-red-700 placeholder-red-400`;
    }
    
    if (fieldName === 'username' && username.length >= 2 && usernameAvailable === true) {
      return `${baseClasses} border-green-400 focus:ring-green-400 focus:border-green-400 bg-green-50 text-green-700 placeholder-green-400`;
    }
    
    return `${baseClasses} hover:border-neutral-400`;
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-stone-100 to-amber-100 flex items-center justify-center font-sans">
        <div className="animate-spin h-10 w-10 border-4 border-amber-500 rounded-full border-t-transparent"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-stone-100 to-amber-100 flex justify-center items-center p-4 font-sans">
      <div className="w-full max-w-lg bg-white p-8 md:p-10 rounded-xl shadow-2xl">
        <div className="mb-8 text-center">
          <h1 className="text-3xl md:text-4xl font-serif font-medium text-stone-800">Complete Your Profile</h1>
          <p className="mt-2 text-stone-600">Help us personalize your experience.</p>
        </div>

        {error && (
          <div className="mb-6 p-3.5 bg-red-100 text-red-700 text-sm rounded-lg border border-red-200 transition-all duration-300 ease-in-out animate-fadeIn">
            {error}
          </div>
        )}

        {success && (
          <div className="mb-6 p-3.5 bg-green-100 text-green-700 text-sm rounded-lg border border-green-200 transition-all duration-300 ease-in-out animate-fadeIn">
            Profile updated successfully! Redirecting...
          </div>
        )}
        
        {autoGeneratedUsername && !success && (
          <div className="mb-6 p-3.5 bg-sky-100 text-sky-700 text-sm rounded-lg border border-sky-200 transition-all duration-300 ease-in-out animate-fadeIn">
            We noticed your username might be auto-generated. Feel free to choose one you prefer!
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-5 w-full" noValidate>
          <div className="flex gap-4">
            <div className="w-1/2">
              <input
                id="firstName"
                name="firstName"
                type="text"
                className={getInputClasses('firstName')}
                placeholder="First name"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                onBlur={handleBlur}
                required
              />
              {touchedFields.firstName && customValidation.firstName && (
                <p className="mt-1 text-sm text-red-500">{customValidation.firstName}</p>
              )}
            </div>
            
            <div className="w-1/2">
              <input
                id="lastName"
                name="lastName"
                type="text"
                className={getInputClasses('lastName')}
                placeholder="Last name"
                value={lastName}
                onChange={(e) => setLastName(e.target.value)}
                onBlur={handleBlur}
                required
              />
              {touchedFields.lastName && customValidation.lastName && (
                <p className="mt-1 text-sm text-red-500">{customValidation.lastName}</p>
              )}
            </div>
          </div>
          
          <div>
            <div className="relative">
              <input
                id="username"
                name="username"
                type="text"
                className={getInputClasses('username')}
                placeholder="Username"
                value={username}
                onChange={handleUsernameChange}
                onBlur={handleBlur}
                required
              />
              {isCheckingUsername && (
                <div className="absolute right-3 top-1/2 transform -translate-y-1/2">
                  <div className="animate-spin h-5 w-5 border-2 border-slate-500 rounded-full border-t-transparent"></div>
                </div>
              )}
              {!isCheckingUsername && username.length >= 2 && usernameAvailable === true && (
                <div className="absolute right-3 top-1/2 transform -translate-y-1/2 text-green-500">
                  ✓
                </div>
              )}
            </div>
            {touchedFields.username && customValidation.username && (
              <p className="mt-1 text-sm text-red-500">{customValidation.username}</p>
            )}
            {!customValidation.username && username.length >= 2 && usernameAvailable === true && (
              <p className="mt-1 text-sm text-green-500">Username is available</p>
            )}
            {!customValidation.username && username.length >= 2 && usernameAvailable === false && (
              <p className="mt-1 text-sm text-red-500">Username is already taken</p>
            )}
          </div>

          <div>
            <button
              type="submit"
              className="w-full flex items-center justify-center px-4 py-3.5 bg-stone-800 text-white rounded-lg shadow-md hover:bg-stone-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500 transition-all duration-200 ease-in-out transform hover:scale-[1.01] active:scale-[0.99] disabled:opacity-70 disabled:cursor-not-allowed"
              disabled={isSaving || success} // Disable if success to prevent multi-submit before redirect
            >
              {isSaving ? (
                <>
                  <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Saving your profile...
                </>
              ) : (
                <div className="flex items-center">
                  <span className="mr-2">→</span>
                  <span>Save profile & Continue</span>
                </div>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
} 